In [1]:
import numpy as np

So here we make a proxy for the actual CIFAR-10 data to understand how to reshape it. CIFAR-10 is in "chunks", each chunk is 10,000 by 3072. Each data point is in the range [0,255] as uint8. Row major order, so it something like this:


[0][1024 red values][1024 blue values][1024 green values]
Where in row[i] we have:
[1-31] row 1 of red values
[32-63] row 2 of red values
...
[992-1023] row 32 of red values
[1-31] row 1 of green


In [4]:
x = np.arange(120) + 1
x = x.reshape(2,60) #this is a proxy for my data array above - we have 2 'images' here
x = x.reshape(2,3,4,5) # 2 imgs, 3 channels, a 4 rows, 5 columns

print(x)

x = x.transpose(0,2,3,1).astype("uint8") # so we make it 2 imgs, 4 rows, 5 cols, 3 channels

print(x)


[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]
[[[[  1  21  41]
   [  2  22  42]
   [  3  23  43]
   [  4  24  44]
   [  5  25  45]]

  [[  6  26  46]
   [  7  27  47]
   [  8  28  48]
   [  9  29  49]
   [ 10  30  50]]

  [[ 11  31  51]
   [ 12  32  52]
   [ 13  33  53]
   [ 14  34  54]
   [ 15  35  55]]

  [[ 16  36  56]
   [ 17  37  57]
   [ 18  38  58]
   [ 19  39  59]
   [ 20  40  60]]]


 [[[ 61  81 101]
   [ 62  82 102]
 

So with the new layout, lets say we want to print the first image, second row, third col, red channel. What value should we expect? Run the next block to check your answer.

In [5]:
print(x[0][1][2][0]) #first image, second row, third column, 1st (red) channel

8
